### ISSUE TITLE
Add example using vite-plugin-ssr

### ISSUE THREAD

**Issue by brillout** [HoudiniGraphql/houdini#1072]
### Describe the feature

Is supporting tools like [vite-plugin-ssr](https://vite-plugin-ssr.com) on Houdini's roadmap?

With vite-plugin-ssr, users integrate tools manually. The upside of manual integration is that users can use any tool they want and however they want. (E.g. some users use vite-plugin-ssr to deeply integrate with Relay which isn't possible with Next.js nor Remix.)

Is there a guide on how to integrate Houdini?

Congrats on Houdini, it looks really neat!

### Criticality

waiting for it to switch all my project to Houdini

**Comment by AlecAivazis** [comment]
:D Thanks for the kind words! At the moment, we haven't really explored `vite-plugin-ssr` for our svelte integrations since so much of the community relies on Kit. That being said, there's nothing stopping someone from using the generated stores inside of the render function so it would probably be good to put an example together. Unfortunately, I don't have a lot of time right now so i'm not sure when I'll get to it but I'll leave this issue up in case someone gets to it first.

That being said, for our react integration, `vite-plugin-ssr` is very much on my radar. I am still trying to work through a lot of those details but my plan for this weekend was to start exploring the SSR side of the story and that journey was going to start with `vite-plugin-ssr`.

**Comment by brillout** [comment]
Makes sense!

My general thinking is that since vite-plugin-ssr is lower level it can be a good showcase for meta framework authors on how to integrate Houdini. Although, on the other hand, if Houdini can be integrated with Next.js on the user land then that would suffice and probably be a better showcase.

(In principle, if something can be integrated in Next.js user land, then it very likely can also be integrated into vite-plugin-ssr. Integrating with vite(-plugin-ssr) is usually much easier than intergrating with Next.js so that may be a good start.)

Very much looking forward to the Houdini future 👀. AFAICT GraphQL and RPC will completely supersede API routes and REST (and I guess that using them will feel like using webpack instead of a meta framework).
