### ISSUE TITLE
`fetching` is always `false` and `source` is always `"cache"`

### ISSUE THREAD

**Issue by milan-gm** [HoudiniGraphql/houdini#1102]
### Describe the bug

When pagination is used fetching is always `false` for every time I trigger `loadNextPage()`. Also the `source` is always showing `cache` even when I choose the `NetworkOnly` policy.

### Severity

serious, but I can work around it

### Steps to Reproduce the Bug

The query:
``` gql
# +page.gql
query TagsList($text: String) {
  tags(text: $text, first: 20, discarded: false) @paginate(name: "Tags") {
    totalCount
    edges {
      node {
        id
        name
      }
    }
  }
}
```

The page:
``` svelte
+page.svelte
<script>
  export let data: PageData;
  $: ({ TagsList } = data);

  const loadMore = () => {
    if ($TagsList.pageInfo.hasNextPage) TagsList.loadNextPage();
  };
</script>
```

The TagsList store result:
``` js
{
    // ...
    "errors": null,
    "fetching": false, // always false :(
    "partial": false,
    "stale": false,
    "source": "cache", // always cache :(
    "variables": {},
    "pageInfo": {
        "hasPreviousPage": false,
        "hasNextPage": true,
        "startCursor": "MQ",
        "endCursor": "MzA"
    }
}

### Reproduction

_No response_

**Comment by AlecAivazis** [comment]
Hey @milan-gm!

So it might be a little confusing but this is actually expected. The network fetches that happens when loading pages does not impact the loading state of the store. This is because the store's loading state is meant to be used to power skeleton UIs that replace the full contents whereas the pagination fetch loading state is usually represented in a separate way. If you want to draw a loading indicator for the pagination fetches i suggest maintaining some state in your component that you update

**Comment by milan-gm** [comment]
Hey @AlecAivazis thanks for the response. I find this to be confusing and unintuitive though and I'm almost certain that other people will have the same problem as me. The word `fetching` to me indicates that a network request is being made.

As an alternative another `loading` store could be created to serve this purpose like superforms does:
https://superforms.vercel.app/concepts/timers#loading-indicators
