### ISSUE TITLE
Could not find required variable function

### ISSUE THREAD

**Issue by andrejohansson** [HoudiniGraphql/houdini#1323]
### Describe the bug

When I try to make an [api endpoint](https://houdinigraphql.com/api/query#api-route--endpoint) I get a build error. These are the only two files in the folder. Am I doing something wrong or is this a bug (I am very new to this lib)?

```
❌ Encountered error in src/routes/api/search/+page.js
Could not find required variable function: _FindShopsByNameVariables. maybe its not exported?
```

I am using 

```json
        "houdini": "^1.2.48",
        "houdini-svelte": "^1.2.48",
```

**src\routes\api\search\+page.gql**

```graphql
query FindShopsByName($name: String!) {	
	searchShopsV2(text: $name ) {
		hits {
			shopId
			name
			market
		}
  }
}
```

**src\routes\api\search\+server.ts**

```typescript
import { json, error } from '@sveltejs/kit';
import { FindShopsByNameStore } from '$houdini'
import type { RequestHandler } from './$types';

export const GET: RequestHandler = async (event) => {
    try {
        const searchTerm = event.url.searchParams.get('q');

        if (searchTerm === null) {
            return error(400, 'Missing search term');
        }
       
        // https://houdinigraphql.com/api/query#api-route--endpoint
        const query = new FindShopsByNameStore()
        const { data } = await query.fetch(
            {                 
                event,                
                variables: {                    
                    name: searchTerm
                }
            }
        );

        return json(data?.searchShopsV2?.hits, { status: 200 });
    } catch (err) {
        console.error(err);
        return error(500, 'Failed to query shops');
    }
}
```

**Comment by SeppahBaws** [comment]
Hi,
When you put a query in a `+page.gql`, Houdini will automatically load the query when the page gets loaded (so that its data can also come with the SSR response).

In order to do this, Houdini also needs to know what variables it needs to pass in to the query. The easiest way to do this is with a `_MyQueryVariables` function. Take a look at the [Automatic Loading](https://houdinigraphql.com/api/query#automatic-loading) section on the docs on how to do this.
