### ISSUE TITLE
Querying outside of .svelte files?

### ISSUE THREAD

**Issue by eden-omb** [HoudiniGraphql/houdini#218]
I don't understand the underlying complexity, I know a lot of the point of houdini is to take queries in pages into endpoints. However, I was trying to refactor a page's queries into a little util file and simply import the query stores into the page, and got the following error:
```
Looks like you don't have the preprocessor enabled.
Error: Looks like you don't have the preprocessor enabled.
    at Module.graphql (/$houdini/runtime/index.js:12:11)
    at /src/routes/catalog/_db.js
```
Is there any way to support this, or will I always have to only use queries in the .svelte pages proper?

**Comment by AlecAivazis** [comment]
Hey @eden-omb, thanks for checking out houdini. I think you are slightly confused about the overall approach. Houdini does not try to push queries to endpoints but instead lets you define your queries inside of your pages/components and handles the rest. It does this be generating the corresponding `load` function for a given page. Because of this, you must define your query inside of a .svelte file that the preprocessor can manipulate. 

If you have a query that you want to reuse in multiple parts of you app, i suggest building a component that either uses and query or fragment and then reusing that where you need the information.

**Comment by AlecAivazis** [comment]
Closing this to keep things tidy. Please let me know if you need more help
