### ISSUE TITLE
Make load hooks more versatile

### ISSUE THREAD

**Issue by fehnomenal** [HoudiniGraphql/houdini#232]
On the page I'm building with kit I need to display categories for a navigation component and want to highlight the active category (the currently viewed category or the category of the currently viewed entry). I see 3 possible approaches:

1. I could just retrieve the categories on each page where I need them, extract somehow the active category and give those as props to the `Navigation` component. This would mean much duplicated code and I think I would need to find an unique name for each query, right? Also it would be not good for caching, right?
2. Retrieve the categories in `__layout.svelte`, put them into a context and extract them where needed.
3. Retrieve the categories in `__layout.svelte` and pass them to further pages via the `stuff` property. This would mean that the `afterLoad` hook may return an `LoadOutput` object.

I think the third option would be the best (at least for kit, I did not look into how the kit code is wrapped for sapper) and implemented a PoC which works alright. Basically my modified code generates this as the `load` return:
```js
  const _houdini_props = {
    _GetCategoriesPublic,
    _GetCategoriesPublic_Input: {},
    _GetCategoriesPublic_Source
  };
  if ("props" in _houdini_context.returnValue)
    return {
      ..._houdini_context.returnValue,
      props: {
        ..._houdini_context.returnValue.props,
        ..._houdini_props
      }
    };
  return {
    props: {
      ..._houdini_context.returnValue,
      ..._houdini_props
    }
  };
```

The fallback means I have to return something for the `props` key in `__layout.svelte`s `afterLoad`:
```js
    return {
      props: {},
      stuff: {
        categories: data.GetCategoriesPublic.categories,
      },
    };
```

Would you be willing to implement something like this/accept a PR for this?

Then I would polish the code a bit and also handle returns from both `beforeLoad` and `afterLoad`.

**Comment by AlecAivazis** [comment]
Hey @fehnomenal! I'm a little distracted at the moment with some other work for Houdini so I haven't found the time to look at your proposal but I will get to it as soon as I have some time. I didn't want you to think I was ignoring you. Thanks for being patient!

**Comment by AlecAivazis** [comment]
I think you're right that the third option is probably best and could be a useful improvement for many other use cases. Feel free to open a PR if you're still interested, i'd love to take a look :)

**Comment by fehnomenal** [comment]
Glad you like it and that I can contribute to this great project :)

I will prepare a PR but will probably need your help for adding some test cases :sweat_smile:

**Comment by AlecAivazis** [comment]
Hah totally understandable! The test cases for the preprocessor rely on snapshot tests which don't really verify the behavior as much as make sure that the same output is generated for every situation. Since you are about to change what the preprocessor leaves behind it's going to look a bit scary at first since you will break every test - just press `u` if you are using the `tests:watch` command, otherwise pass `-u` and that will update the snapshots and make everything pass. Unfortunately since it doesn't confirm that the behavior is actually implemented, I'll have to pull down the branch and run it in a test project to verify things.

**Comment by AlecAivazis** [comment]
Also, in reponse  to `Also it would be not good for caching, right?`, it actually has no impact on the caching behind the scenes since presumably both queries (which did need unique names) would be querying for the same field. This just means that two stores are subscribing to the same value in the cache. In fact, with the right [CachePolicy](https://www.houdinigraphql.com/api/query#caching-data) and code organization you could even avoid the extra queries all together.

**Comment by AlecAivazis** [comment]
Closing this since #238 got merged. Thanks again :)
