### ISSUE TITLE
Query batching

### ISSUE THREAD

**Issue by SorenHolstHansen** [HoudiniGraphql/houdini#285]
It would be great to enable query batching at some point. It is probably not a priority, but a nice feature for the future

**Comment by AlecAivazis** [comment]
Totally! I think for now these kinds of things can be reasonably left for userland since someone could implement batching as part of their `fetchQuery` function in their environment definition but we probably want to think of the right way to allow for this kind of customization. Maybe something like urql exchanges?

**Comment by AlecAivazis** [comment]
Closing this in favor of #365
