### ISSUE TITLE
Add option to configure the config file path

### ISSUE THREAD

**Issue by AlecAivazis** [HoudiniGraphql/houdini#302]
### Discussed in https://github.com/HoudiniGraphql/houdini/discussions/300

<div type='discussions-op-text'>

<sup>Originally posted by **tadeokondrak** May 23, 2022</sup>
I'm working on a project where the frontend isn't at the root of the workspace. Most things work fine, but the Svelte language server needs to run the preprocessor to find errors, and since it runs in the root of the workspace, it shows an error in many files:

`Cannot find module '.../repo/houdini.config.js' imported from .../repo/frontend/houdini/build/preprocess-esm/index.js`

The file structure is something like:
```
repo/
repo/frontend/svelte.config.js
repo/frontend/houdini.config.js
repo/frontend/$houdini/...
repo/backend/...
```

I'm not sure what the best way to fix this is. Should the language server be running the preprocessors in the directory with svelte.config.js, or can Houdini do something to look for the config differently?</div>

**Comment by alexlafroscia** [comment]
I'm running into the same issue with my own application that has a SvelteKit app in a workspace.

Ideally, the `houdini` preprocessor could optionally take an explicit path to the configuration file, so that you can avoid looking up the file in the default location based on `process.cwd()`, since doing so doesn't always work well with a monorepo set-up.

**Comment by AlecAivazis** [comment]
I'm a bit swamped with #291 so if anyone wants to take this on i'd be happy to provide any guidance they need either here or directly on discord

**Comment by AlecAivazis** [comment]
#302 adds a `configFile` parameter to the preprocessor. Hopefully that addresses your needs 👍
