### ISSUE TITLE
Unable to use Graphql-Modules files as schema source for Houdini

### ISSUE THREAD

**Issue by nikfp** [HoudiniGraphql/houdini#388]
Hello, 

I was wondering if there is support in Houdini for compiling Graphql schemas from Graphql-Modules files. Typically partial schemas are expressed as tagged template literals using the `gql` tag supplied by Modules. Graphql-Code-Generator has no issue picking these up, and KitQL worked with them also. However when I tried using a glob pattern as the schema source for Houdini I was hitting an error, something about saying it didn't like the `import` keyword at the beginning of the file which tells me it isn't parsing the file as expected. 

If there is a recommended way to work with this, that would be awesome. In the meantime I found a workaround, using Codegen to generate in introspection file and pointing Houdini to the introspection file as the schema. 

Let me know what you think. I also tried to post this in Discussions instead of issues but GIthub wasn't having it for some reason.

**Comment by jycouet** [comment]
What you are putting together is exactly the point of KitQL (using Houdini for the client part and Yoga for the server part).
Check out this [Demo2](https://www.kitql.dev/docs/demos/03_demo-02), I think that it's exactly what you want to setup. 

For schema files, instead of putting them in a `ts` files, you can put them in a `.graphql` files.
Like this, in the Houdini config, you will do:
[demo2 - houdini.config.js](https://github.com/jycouet/kitql/blob/main/examples/demo2/houdini.config.js)
```
{
    schemaPath: 'src/**/*.graphql',
    sourceGlob: 'src/**/*.{svelte,gql}',
}
```

Maybe we can have a direct chat on DIscord or so?
