### ISSUE TITLE
Data is not updated without page reload

### ISSUE THREAD

**Issue by phenomen** [HoudiniGraphql/houdini#408]
```html
<script context="module">
	export function DataVariables({ params }) {
		return {
			lang: params.lang ? params.lang : 'en'
		};
	}
</script>
<script lang="ts">
	import { query, graphql } from '$houdini';
	
	const { data, loading } = query(graphql`
		query Data($lang: Locale!) {
			categories(locales: [$lang]) {
				stuff
			}
		}
	`);
</script>
```

Data is updated when I go from `/en` to `/ua` but when I click on `/en` again, the data stays the same as `/ua` instead of being read from cache and updated in the DOM.
```html
<!-- header navigation -->
<a href="/en">
<a href="/ua">
```

This works but I don't like the idea of forced reload.
```html
<a sveltekit:reload href="/en">
<a sveltekit:reload href="/ua">
```

**Comment by AlecAivazis** [comment]
Hey @phenomen sorry you are running into this! Is your project pushed up somewhere I can pull and debug it?

**Comment by phenomen** [comment]
> Hey @phenomen sorry you are running into this! Is your project pushed up somewhere I can pull and debug it?

Hi @AlecAivazis . Here is it https://github.com/phenomen/dnd5-ref-next

**Comment by AlecAivazis** [comment]
Okay, I was able to reproduce your issue and have a good idea what's going on.

Basically the core issue is that the `id` field does not uniquely define your record values. Instead, Categories, Subcategories, and Items are defined by the combination of `id` and `locale` fields. To make this concrete/think out loud: say you start on `/ph`, the cache has a value for `categories(locales: [ph, ph])`, `subcategories(locales: [ph, ph])`, and `items(locales: [$lang, ph])` and ultimately some `Item`, let's say it has id `4` with the name `Движение`. When you click into `/hw` the cache looks to see if it has values for `categories(locales: [hw, ph])` and the rest. It doesn't, so it queries the API to get that information and the response has the same Item with id `4`  but this time it sees a new name `Перемещение` so it writes that value to cache. When you click back to `/ph`, the cache already has a value for `categories(locales: [ph, ph])` from the initial load so it pulls those values, including the Item with id 4 which has the new value from the `hw` locale.

In order to address this, Houdini lets you specify a `keys` field in the `types` object of your config file where you can pass the list of fields to use when generating IDs ([link to docs](https://www.houdinigraphql.com/guides/caching-data#custom-ids)). I was able to get your application working by adding this to your config file:

```javascript
{
	types: {
		Item: {
			keys: ['id', 'locale']
		},
		Category: {
			keys: ['id', 'locale']
		},
		Subcategory: {
			keys: ['id', 'locale']
		}
	}
}
```

You'll have to add a bit more config if you want to use features like paginated fragments but hopefully that doc link gives you some guidance. To be perfectly honest, I don't think many people have used this feature yet so you might run into some issues but this bit of config only impacts a few places so we should be able to sort through anything you run into. You can always reach out to me on discord for more direct access.
