### ISSUE TITLE
Accessing GQL store while loading in an other route breaks SSR

### ISSUE THREAD

**Issue by janvotava** [HoudiniGraphql/houdini#452]
Demo: https://github.com/janvotava/houdini-error-reproduce-001

When the `$GQL` store is read in the [__layout.svelte](https://github.com/janvotava/houdini-error-reproduce-001/blob/main/src/routes/__layout.svelte#L12), the resulting data in the [routes/index.svelte](https://github.com/janvotava/houdini-error-reproduce-001/blob/main/src/routes/index.svelte#L21) will be `null` for some reason and SSR won't work.

**Comment by AlecAivazis** [comment]
After digging into this a bit, it turns out that the issue is that the store's value gets deleted from the unsubscribe which erases the value being rendered (at least that's my current working model). I have a branch with a failing test here: https://github.com/HoudiniGraphql/houdini/tree/same-store-twice. 

Since fixing this is a slightly larger effort, I'd like to wait until #449 is in so we don't have a lot of conflicts to sift through

**Comment by AlecAivazis** [comment]
I have a hunch that #449 will fix this. hopefully one of us will remember to confirm when its merged
