### ISSUE TITLE
Generated _toggle fragment: id field duplication

### ISSUE THREAD

**Issue by DanielHritcu** [HoudiniGraphql/houdini#510]
The generated toggle fragment has a duplicated `id` field.

```graphql
fragment _AllAccounts_toggle on Account {
  email
  enabled
  id
  id
}
```

I'm not sure, but I think it's caused by:
https://github.com/HoudiniGraphql/houdini/blob/73d67a8b88248c987c61260cd5fff16f62b5da29/src/cmd/transforms/list.ts#L271-L283

as there is a check here:
https://github.com/HoudiniGraphql/houdini/blob/73d67a8b88248c987c61260cd5fff16f62b5da29/src/cmd/transforms/list.ts#L221-L240

and the generated insert fragment has the same selections as the toggle, but does not add the additional `id` field.
https://github.com/HoudiniGraphql/houdini/blob/73d67a8b88248c987c61260cd5fff16f62b5da29/src/cmd/transforms/list.ts#L253

### Severity

annoyance

### Steps to Reproduce the Bug

1. Add a `@list` or `@paginated` directive.
2. Check the generated *_toggle fragment

### Expected behavior

no duplicated fields

### System Info

```shell
System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Max
    Memory: 168.08 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.15.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Safari: 16.1
  npmPackages:
    @sveltejs/adapter-cloudflare-workers: 1.0.0-next.54 => 1.0.0-next.54 
    @sveltejs/kit: 1.0.0-next.465 => 1.0.0-next.465 
    svelte: 3.50.0 => 3.50.0 
    vite: 3.1.0-beta.2 => 3.1.0-beta.2
```

**Comment by AlecAivazis** [comment]
👋 thanks for reporting this.

Is it negatively impacting you in any way? duplicated selections aren't really a "bug" as much as a tiny performance optimization. Since it's just a single field in the same selection set, this would remove one extra step of a for loop when flattening the query at the cost of additional logic to maintain in houdini, not sure it's worth the effort unless it is creating problems
