### ISSUE TITLE
 Error: stores.session is no longer available

### ISSUE THREAD

**Issue by yasserlens** [HoudiniGraphql/houdini#522]
### Describe the bug

Hello!

This is related to the breaking change in SvelteKit which removed access to session data. More details at 
https://github.com/sveltejs/kit/discussions/5883

The error was triggered when calling getHoudiniContext(), 

Sample code in example.svelte:

```
import { getHoudiniContext } from '$houdini';

const context = getHoudiniContext();
```

### Severity

blocking all usage of Houdini

### Steps to Reproduce the Bug

This is triggered on calling getHoudiniContext(); 

### Expected behavior

This error shouldn't happen - see migration guide for SvelteKit:
https://github.com/sveltejs/kit/discussions/5883

### System Info

```shell
System:
    OS: macOS 12.4
  Binaries:
    Node: 16.13.2 - /usr/local/bin/node
    npm: 8.1.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 105.0.5195.102
    Safari: 15.5
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.64 
    @sveltejs/adapter-netlify: ^1.0.0-next.51 => 1.0.0-next.71 
    @sveltejs/kit: ^1.0.0-next.427 => 1.0.0-next.427 
    houdini: ^0.15.9 => 0.15.9 
    svelte: ^3.44.0 => 3.49.0 
    vite: ^3.0.2 => 3.0.2
```

**Comment by AlecAivazis** [comment]
Hello! This should be fixed in the latest `@next` version.  As i'm sure you can imagine, we had to change a lot of things to make houdini work with the big kit update. Here are the release notes on the preview site: https://docs-next-kohl.vercel.app/guides/release-notes.  We are pretty close to releasing the new version so keep an eye out!
