### ISSUE TITLE
Dynamic fragment masking

### ISSUE THREAD

**Issue by fehnomenal** [HoudiniGraphql/houdini#529]
### Describe the feature

Generally I like masking for cleaner separation of concerns and don't want to disable it globally. Right now I have an use case where I would like to disable masking for one specific query:

I use felte for a form to edit a record. The record/form has many fields which can be easily divided into categories (these become individual components and I would like to split the query into fragments corresponding to the components). Felte can take a generic argument to type the form data e.g. for the submit handler. Now just doing `createForm<ThingFromGraphql$result>()` results in the type having only the `$fragments` property and is thus useless for typing...

I would love to be able to write the following:
![image](https://user-images.githubusercontent.com/9959940/189430792-be74111a-0c1b-4c56-a9e3-a176e11aead6.png)
(Probably the directive is at the wrong location but you get the idea)

And instead of `$fragments`
![image](https://user-images.githubusercontent.com/9959940/189431214-00fe9a9f-d34d-4296-bb1d-bf900ff38fd8.png)
there would be all fields in the type.

Would this be possible to implement? I did not yet dive too deep into the artifact generation code. But IIRC this should only affect the generated types, right? As the data returned by the query is complete when logging to the console.

### Criticality

cool improvement, my projects will benefit from it

**Comment by AlecAivazis** [comment]
This is absolutely something we want to support! I meant to do it as part of the #357 but didn't want to get too distracted while working on `0.15.0`.  If we're nitpicking names, I think I prefer `mask` to `masking` 🤷‍♂️ 

You're right that this really just affects the type generator. It does introduce some complexity since a field might be masked in one fragment that's mixed in and not masked in another but it shouldn't be too hard to work around.

**Comment by AlecAivazis** [comment]
Turns out i _did_ make an issue for this awhile ago: https://github.com/HoudiniGraphql/houdini/issues/349. Let's close this in favor of that one (i'll update your PR description)
