### ISSUE TITLE
Loading in layouts broken?

### ISSUE THREAD

**Issue by endigma** [HoudiniGraphql/houdini#541]
### Describe the bug

Any query, inline or not, seems to fail when in a `+layout.svelte` or `+layout.ts` file.

### Severity

serious, but I can work around it

### Steps to Reproduce the Bug

files:
- `+page.svelte`, content irrelevant
- `+layout.svelte`, inline query of anything and a usage of it
- store will always be undefined

### Reproduction

https://github.com/endigma/houdini-repro

**Comment by endigma** [comment]
In addition, having `+layout.ts` *at all* breaks all queries.

**Comment by AlecAivazis** [comment]
Hm, I suspect something subtle is going on here since I am able to add a query to the integration test's root layout file. There does seem to be a problem with the sessions which I am hunting down now but queries that don't care about the session vlaue are firing no problem for me. If you have the time to debug this on discord, it'd probably be faster than going back and forth on comments here

**Comment by endigma** [comment]
My tag is `@endigma#4426`

**Comment by endigma** [comment]
[Minimal (?) Reproduce](https://github.com/endigma/houdini-repro)
