### ISSUE TITLE
SvelteKit types do not exist at route error

### ISSUE THREAD

**Issue by xmlking** [HoudiniGraphql/houdini#733]
### Describe the bug

I have a directory under routes, that doesn't have  any pages (just some components)
Ref: 
https://github.com/xmlking/svelte-starter-kit/tree/main/src/routes/(app)/dashboard

I am getting the following error from Houdini plugin

<img width="1364" alt="Screenshot 2022-11-29 at 9 48 05 PM" src="https://user-images.githubusercontent.com/627951/204717786-c0aeef7d-eb5a-4521-823b-e72c93515f2d.png">

### Severity

annoyance

### Steps to Reproduce the Bug

- clone repo https://github.com/xmlking/svelte-starter-kit
- change branch feature/houdini
- npm run dev

### Reproduction

https://github.com/xmlking/svelte-starter-kit/tree/main/src/routes/(app)/dashboard

**Comment by AristideBH** [comment]
I can also confirm this behaviour with the following packages on Windows : 
        "@sveltejs/adapter-auto": "next",
        "@sveltejs/kit": "next",
        "graphql": "^15.8.0",
        "houdini": "^0.17.14",
        "houdini-svelte": "^0.17.14",
        "svelte": "^3.53.1",
        "vite": "^3.2.4"

**Comment by AlecAivazis** [comment]
Sorry to hear you are running into this. If one of you wants to push a fix through, the logic that generates these types lives [here](https://github.com/HoudiniGraphql/houdini/blob/main/packages/houdini-svelte/src/plugin/codegen/routes/index.ts).

**Comment by 524c** [comment]
> 

Hey @xmlking,

I had a look at your repo, and it looks like the problem is because inside src/routes, Svelte only sees these files:
+page
+error
+layout
+server

You might consider moving these components inside blocks to src/lib/components/

In this link you can see the documentation about this point: https://kit.svelte.dev/docs/routing#other-files

**Comment by 524c** [comment]
Hey @AlecAivazis, 

I debugged [houdini-svelte/src/plugin/codegen/routes/index.ts](https://github.com/HoudiniGraphql/houdini/blob/main/packages/houdini-svelte/src/plugin/codegen/routes/index.ts) and [main/packages/houdini-svelte/src/plugin/kit.ts](https://github.com/HoudiniGraphql/houdini/blob/main/packages/houdini-svelte/src/plugin/kit.ts), and from what I understand, it shouldn't have this throw because Sveltekit only generates types for valid files (+page, +error, +layout, +server) for routes and ignores the rest. So, recursive walk_routes stops traversing the directory tree when it doesn't find a type, and for routes that Svelte ignores, it won't even have $types.d.ts.

[Svelte $types documentation](https://kit.svelte.dev/docs/routing#$types)

Do you think this PR would be viable?

[main/packages/houdini-svelte/src/plugin/kit.ts](https://github.com/HoudiniGraphql/houdini/blob/main/packages/houdini-svelte/src/plugin/kit.ts#L275)
```diff
+ // if type does not exists we return.
+ if (!fs.existsSync(svelteTypeFilePath)) {
+   return
+ }

- // if type does not exists we error.
- if (!fs.existsSync(svelteTypeFilePath)) {
-  throw Error(`SvelteKit types do not exist at route: ${svelteTypeFilePath}`)
- }
```

**Comment by sjcobb2022** [comment]
Most likely has to do with special characters (e.g. \( ) in a route. I'll take a look later today.

**Comment by sjcobb2022** [comment]
I made a pull request here and added further tests

**Comment by AlecAivazis** [comment]
So I actually prefer @524c's fix without the warning. There's nothing inherently _wrong_ with a user not having kit route files in a directory. I'd like to treat the user like they know what they're doing. Since it was @524c's fix originally, i think we should let them open the PR with their contribution

**Comment by 524c** [comment]
Honestly, I also prefer not to have alerts, since not having types in certain routes is a normal behavior of Svelte.

I have a change from the previous proposal. Instead of the `return` we need a `continue` and let the `walk_routes` go on with its normal life.

I see my PR only as a patch, I couldn't see any possible new test 🤔

@sjcobb2022, can you think of any tests?

```javascript
// if type does not exists we return.
if (!fs.existsSync(svelteTypeFilePath)) {
  continue
}
```

**Comment by sjcobb2022** [comment]
> So I actually prefer @524c's fix without the warning. There's nothing inherently _wrong_ with a user not having kit route files in a directory. I'd like to treat the user like they know what they're doing. Since it was @524c's fix originally, i think we should let them open the PR with their contribution

Alright I'll close mine

**Comment by sjcobb2022** [comment]
> Honestly, I also prefer not to have alerts, since not having types in certain routes is a normal behavior of Svelte.
> 
> I have a change from the previous proposal. Instead of the `return` we need a `continue` and let the `walk_routes` go on with its normal life.
> 
> I see my PR only as a patch, I couldn't see any possible new test 🤔
> 
> @sjcobb2022, can you think of any tests?
> 
> ```javascript
> // We will only visite valid routes for Svelte.
> if (!fs.existsSync(svelteTypeFilePath)) {
>   continue
> }
> ```
> 

I implemented some e2e checks so that we don't get the behaviour in the future but they aren't necessary in all honesty.

**Comment by 524c** [comment]
> > Honestly, I also prefer not to have alerts, since not having types in certain routes is a normal behavior of Svelte.
> > I have a change from the previous proposal. Instead of the `return` we need a `continue` and let the `walk_routes` go on with its normal life.
> > I see my PR only as a patch, I couldn't see any possible new test 🤔
> > @sjcobb2022, can you think of any tests?
> > ```js
> > // We will only visite valid routes for Svelte.
> > if (!fs.existsSync(svelteTypeFilePath)) {
> >   continue
> > }
> > ```
> 
> I implemented some e2e checks so that we don't get the behaviour in the future but they aren't necessary in all honesty.

Ok, so I believe that if you find it necessary, you can do a PR with the tests.
My previous comment about a `continue` instead of a `return` is not right. The visite route is after the for.. 🤦
