### ISSUE TITLE
Store Names Starting With "GQL_" Not Supported Anymore?

### ISSUE THREAD

**Issue by jaming715** [HoudiniGraphql/houdini#833]
### Describe the bug

I've been using houdini for my project for a couple of months now and really like it. I just updated to the latest version and my whole project broke because I was using store names starting with "GQL_", primarily to run all of my mutations defined in ".gql" files. I see this functionality has changed. Do we now have to import the store with the new naming convention and instantiate it before using it? Please confirm that this is now the case and it should work in the same way. Is there any way to keep track of breaking changes properly? I had to infer this was the case by sifting through the docs and not finding anything about "GQL_" stores. My entire project stopped working and was very confused as I could not find anything pointing to this change. I really enjoy working with your project, but keeping track of breaking changes and the changing documentation on the site can be very confusing. If there is a proper way to keep track of these changes?

### Severity

annoyance

### Steps to Reproduce the Bug

1. Attempt to import a mutation store starting with "GQL_"
2. Receive an error stating "The requested module '/$houdini/index.js' does not provide an export named "GQL_..."

**Comment by AlecAivazis** [comment]
Oh my! Sorry to hear that was such a rough experience for you. The global stores were removed in `0.19.0` since there were a lot of caveats to their use. But don't worry - you can easily bring them back with the `houdini-plugin-svelte-global-stores` package. The instructions for how to do that are found in the [release notes for v0.19.0](https://www.houdinigraphql.com/guides/release-notes#0190).

I've been trying to keep the release notes up to date with migration instructions so you should be able to use that to track anything major 👍

**Comment by AlecAivazis** [comment]
No problem at all! Hopefully I can answer your questions and clear up some of the confusion.

>  From what I understand a svelte store is simply a way to share data throughout the entire application. How is that different from a global store? If I were to instantiate a store for a mutation like "new MutationStore()" in two different places in my app, would this be the same underlying svelte store or would they be two different ones?

This is mostly a concern for SSR. The `GQL_` stores were "global" in the sense that they were single instances of a store that existed in the server's memory. This meant it was very easy to load private data into a store and then accidentally show it to an unintended user. If you were using the `GQL_` query stores, you had to be very careful.  The same is true for mutations, and subscriptions but those are usually client-specific situations so the issues are much rarer there.

In most situations, there are easier ways of sharing data to multiple places in your app. My personal favorite is to add it to a `+layout.gql` file at the very root of your application which will make the query results available to every route in your app. I do this all the time for user session information.

That being said, if all you are using the `GQL_` stores for is mutations, then I would recommend adding the plugin and continue using them since they are convenient. Just remember that their value might be leaked to other users during SSR if you aren't careful.

**Comment by jycouet** [comment]
Reading this, I just got an idea 💡

Why don't we add in the `svelte-global-stores` plugin an option to generate types of stores? 
And by default, only mutations & subscriptions but no queries? 

```js
{
  plugins: {
    'houdini-plugin-svelte-global-stores': {
      prefix: 'GQL_',
      storeToGenerate: [
        // 'Query', 
        'Mutation', 
        'Subscription',
      ]
    },
  }
}
```

Like this, it's also an `opt-in` to get `Query`

What do you think? _(Not hard to do... But also not sure it's 100% useful to do)_

**Comment by AlecAivazis** [comment]
> which is different from the previous behavior where you would use the same store to execute a given query everywhere in your app?

Sounds like you're on the right track! Whether the old value was used or not depends a LOT on the details of the fetch function but that complexity is exactly why it was considered an anti-pattern. I'm going to close this since your original request is satisfied.

@jycouet seems like a nice config value to offer. I'm a bit wary of having `Query` be disabled by default because then its a breaking change. Although, I suppose `1.0` is the right time for it?
