### ISSUE TITLE
Hash doesn't match artifact text

### ISSUE THREAD

**Issue by trmcnvn** [HoudiniGraphql/houdini#936]
### Describe the bug

In 1.0+, the hash value on the artifact is based on the document which doesn't match the raw string on the artifact object. Previous versions of Houdini based the hash on the raw string, so this wasn't an issue for us.

When dealing with a backend GraphQL server that does hash validation, the query fails as it won't match.

Example:

```js
﻿﻿console.log('ctx.hash', ctx.hash);
console.log('ctx.text', crypto.createHash('sha256').update(ctx.text).digest('hex'));
```

```
ctx.hash da885d28ffb8639514dd0f37efdf90ec9ddbb1dab530c1fde0c584c452d3950b
ctx.text 0393633e889973d3f5d248751745eda8888794ff6080889e1ecfeeb87cd70336
```

### Severity

blocking an upgrade

### Steps to Reproduce the Bug

Hash the value of `ctx.text` and compare to `ctx.hash`.

**Comment by AlecAivazis** [comment]
Ah damn! Sorry about that. I have no problems reverting back to the old way. [Here](https://github.com/HoudiniGraphql/houdini/blob/65c5066bffb296b6c9adb6d99a40807a15b716e2/packages/houdini/src/lib/graphql.ts#L23-L37) is where that lives if you want to submit a PR.

**Comment by fehnomenal** [comment]
When we do this could we also minify the generated documents in production? It should have no influence on the hash then.

**Comment by AlecAivazis** [comment]
The more I think about this, the more I am inclined to keep the current behavior since it ensures that we can accurately report changed documents across version updates. @trmcnvn for situations like what you're running into, I suggest adding a [client plugin](https://houdinigraphql.com/api/client-plugins) that sets the outbound hash to whatever your server is expecting
