### ISSUE TITLE
Upgrade to 1.1.0 breaks data fetch when defaultKeys are empty

### ISSUE THREAD

**Issue by yaroslavros** [HoudiniGraphql/houdini#983]
### Describe the bug

After upgrading from 1.0.11 to 1.1.0 I always get data returned as undefined after fetch. Downgrading back to 1.0.11 resolves the issue.

After spending a bit of time reducing my config I figured out that removing `defaultKeys: []` from configuration fixes the issue. In my setup I don't want any caching and used defaultKeys: [] as a way to prevent houdini from auto-injecting id into every query.

### Severity

blocking an upgrade

### Steps to Reproduce the Bug

When defaultKeys are empty, simple page.ts with

```
import { graphql } from '$houdini'

const currentUser = graphql(`
    query User2 {
        users {
            data{username}
        }
    }
`)

export const load = async(event) => {
    console.log(await currentUser.fetch({event}))
}
```

on houdini 1.0.11 produces 

```
{
  fetching: false,
  variables: {},
  data: { users: { data: [Array] } },
  errors: null,
  partial: false,
  stale: false,
  source: 'network'
}
```

on houdini 1.1.0 results in

```
{
  fetching: false,
  variables: {},
  data: { users: null },
  errors: null,
  partial: false,
  stale: false,
  source: 'network'
}
```

**Comment by AlecAivazis** [comment]
Sorry to hear you're running into this. 

With the recent update, fragments get their data by reading from the value that the parent query just wrote to the cache. Because of that, having no ids anywhere will break all sorts of things. 

The best way to turn off caching is to set the default cache policy to `NetworkOnly` which will make everything go to the api. If you want to turn off cache subscriptions in your app, you can do that by adding a client plugin that sets `cacheParams.disableSubscriptions` to true

**Comment by yaroslav-tm** [comment]
Got it, thanks.
Would be good to document that ids are mandatory and empty `defaultKeys` is essentially an invalid configuration.

**Comment by yaroslavros** [comment]
Got it, thanks.
Would be good to document that ids are mandatory and empty `defaultKeys` is essentially an invalid configuration.
