### ISSUE TITLE
Zero-effort type safety

### ISSUE THREAD

**Issue by xmlking** [HoudiniGraphql/houdini#986]
### Describe the feature

with the introduction of [Zero-effort type safety](https://svelte.dev/blog/zero-config-type-safety) in SvelteKit, it would be nice if Houdini also eliminate need for defining PageData types

```diff
<script lang="ts">
-  import type { PageData } from './$houdini';
-  export let data: PageData;
+  export let data;
  let { GetPolicy } = data;
  $: ({ GetPolicy } = data);
</script>
```

### Criticality

None

**Comment by jycouet** [comment]
Thx for creating the issue.

We are thinking about how to do it, and as of today, there is no trivial answer... But, for sure it's in our mind.
We will keep you posted here 👍

**Comment by sjcobb2022** [comment]
Just to comment on this, these new updates might mess with type generation. I don't have time to test it yet as I don't know the brevity of sveltekits changes. Not sure if I will have time since I'm really busy with lecturs rn.

As for the zero-effort type safety. I'm not quite sure if it is possible currently. Since it's still using the rootDirs to extend the current type system.

It may be possible, however I am unsure as to how typescript deals with overlapping file names. If we were able to take priority of sveltekit with the generated $types.d.ts files then we would definitely be able to do this.

One issue with this may mean that we have to rename ./$houdini to ./$types, or find a way to make Houdini output a ./$types file virtually so that we could still reference ./$houdini.

Alternatively we could have a look at how sveltekit does it and see how they auto deduce their types from ./$types

**Comment by jycouet** [comment]
Probably worth exploring options, yes. Would be great something not too _"hacky"_.

Interesting hint: https://github.com/sveltejs/kit/discussions/6708#discussioncomment-5358640

**Comment by AlecAivazis** [comment]
When we do add this, we should also explore options to add automatic typing for variable functions, hooks, etc.

**Comment by AlecAivazis** [comment]
I'm not sure it's possible to reliably overwrite the files that SvelteKit generates since our plugin runs before theirs (which it has to do in order to process `load` functions). I don't think we should push on this until SvelteKit provides a real plugin API that we can hook into to piggy back on their definitions. If someone feels very strongly, i'm more than happy to reopen this ticket once we know its at least feasible
